on: push
run-name: ubuntu-latest
jobs:
  sonar:
    runs-on:ubuntu-latest
    steps:
      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_GITHUBACTION }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }} 
