on: push
run-name: self-hosted
jobs:
  sonar:
    runs-on: self-hosted
    steps:
      - name: SonarQube Scan
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_GITHUBACTION }}
          SONAR_HOST_URL: ${{ secrets.SONAR_URL }}
