on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: mvn clean install
      
     
   
  
      # - name: SonarQube Scan
      # - uses: kitabisa/sonarqube-action@v1.2.0
      #   with:
      #    host: ${{ secrets.SONAR_URL }}
      #    login: ${{ secrets.SONAR_GITHUBACTION}}
